#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-receive".

echo look at me I am the post-commit script
pwd
echo $@
